version: '3.7'

services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  client:
    build: ./client
    ports:
      - "3001:3000"

  mongo:
    image: mongo
    command: --bind_ip_all
    entrypoint:
      - mongo
      - inventoryDB
      - --eval
      - "db.createCollection('items')"
